-- Script de creación de bases de datos para MySQL/MariaDB

DROP DATABASE IF EXISTS ud2_test;
CREATE DATABASE ud2_test;

-- -------------- UD2: SISTEMA DE TEST ONLINE ----------------------- --

USE ud2_test;

DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS EXAMEN;
DROP TABLE IF EXISTS RESPUESTAS;
DROP TABLE IF EXISTS RESULTADOS;

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(15) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(15) NOT NULL,
    MAIL VARCHAR(50) UNIQUE,
    ROL VARCHAR(3) NOT NULL
);

CREATE TABLE EXAMEN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PREGUNTA VARCHAR(500) NOT NULL,
    OPC_A VARCHAR(500) NOT NULL,
    OPC_B VARCHAR(500) NOT NULL,
    OPC_C VARCHAR(500) NOT NULL,
    RESP_MULTI BOOLEAN
);

CREATE TABLE RESPUESTAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EXAMEN INT NOT NULL,
    SOL1 VARCHAR(1) NOT NULL,
    SOL2 VARCHAR(1),
    CONSTRAINT FK_RESPUESTAS_EXAMEN FOREIGN KEY(ID_EXAMEN) REFERENCES EXAMEN(ID)
);

CREATE TABLE RESULTADOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIOS INT NOT NULL,
    INTENTO INT NOT NULL,
    ID_EXAMEN INT NOT NULL,
    RESP1 VARCHAR(1),
    RESP2 VARCHAR(1),
    CORRECTA BOOLEAN,
    CONSTRAINT FK_RESULTADOS_USUARIOS FOREIGN KEY(ID_USUARIOS) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_RESULTADOS_EXAMEN FOREIGN KEY(ID_EXAMEN) REFERENCES EXAMEN(ID)
);

INSERT INTO USUARIOS(USUARIO, CONTRASENA, MAIL, ROL) VALUES("admin", "1234", "admin@testonline.com", "ADM");
INSERT INTO USUARIOS(USUARIO, CONTRASENA, MAIL, ROL) VALUES("usuario1", "123456789", "usuario1@correo.com", "USR");
INSERT INTO USUARIOS(USUARIO, CONTRASENA, MAIL, ROL) VALUES("usuario2", "987654321", "usuario2@correo.com", "USR");
INSERT INTO USUARIOS(USUARIO, CONTRASENA, MAIL, ROL) VALUES("usuario3", "0102030405", "usuario3@correo.com", "USR");

INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Cómo se llaman las variables a las que solamente se accede desde fuera de una función?", "locales", "globales", "iniciales", FALSE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Qué comando se utiliza para imprimir por pantalla?", "screen", "echo", "print", TRUE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Qué método utilizaremos si no queremos que aparezca la información recogida en la barra del navegador web?", "GET", "FROM", "POST", FALSE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Cómo comienza un función definida por el usuario?", "function", "definition", "usrfunc", FALSE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Qué función usaremos para recoger resultados de una base de datos?", "fetch()", "collect()", "fetchAll()", TRUE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Qué función se utiliza para generar un número aleatorio?", "nrdm()", "random()", "rand()", FALSE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Qué tipos de operadores se usan en PHP?", "aritméticos", "metodológicos", "condicionales", TRUE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Qué función se utiliza para devolver la longitud de una cadena?", "cadleng()", "strlen()", "lengcad()", FALSE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Cuáles de estas instrucciones se usan como bucles en PHP?", "while", "for", "make", TRUE);
INSERT INTO EXAMEN(PREGUNTA, OPC_A, OPC_B, OPC_C, RESP_MULTI) VALUES("¿Qué clase de matrices podemos encontrar en PHP?", "validativas", "asociativas", "multidimensionales", TRUE);

INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("1", "B",NULL);
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("2", "B", "C");
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("3", "C", NULL);
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("4", "A", NULL);
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("5", "A", "C");
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("6", "C", NULL);
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("7", "A", "C");
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("8", "B", NULL);
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("9", "A", "B");
INSERT INTO RESPUESTAS(ID_EXAMEN, SOL1, SOL2) VALUES("10", "B", "C");

INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "1", "B",NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "2", "B", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "3", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "4", "C", NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "5", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "6", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "7", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "8", "B", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "9", "A", "B", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "1", "10", "A", "B", "0");

INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "1", "C",NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "2", "B", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "3", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "4", "A", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "5", "B", NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "6", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "7", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "8", "B", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "9", "A", "B", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("3", "2", "10", "B", "C", "1");

INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "1", "A",NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "2", "B", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "3", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "4", "C", NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "5", "B", NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "6", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "7", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "8", "B", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "9", "A", "C", "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "1", "10", "B", "C", "1");

INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "1", "B",NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "2", "B", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "3", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "4", "C", NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "5", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "6", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "7", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "8", "B", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "9", "A", "B", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "2", "10", "A", "B", "0");

INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "1", "B",NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "2", "B", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "3", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "4", "C", NULL, "0");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "5", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "6", "C", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "7", "A", "C", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "8", "B", NULL, "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "9", "A", "B", "1");
INSERT INTO RESULTADOS(ID_USUARIOS, INTENTO, ID_EXAMEN, RESP1, RESP2, CORRECTA) VALUES("4", "3", "10", "B", "C", "1");